Milestone3/evance - TPL version
andrew0928/Andrew.GameOfLifeDemo pull request #19
Opened 2020-11-10 09:07 UTC by EvanceKao

以符合 milestone 3.5 的規格，並以 TPL 方式處理 time events ，以應付大量 lives 需要演算是否演化的情況。

2020-11-10 11:22 UTC, andrew0928 commented
測試沒過

不過速度有提升, 可以達到 160x ...
請以正確性為優先 :D

![image](https://user-images.githubusercontent.com/15281111/98667722-c5be3200-2389-11eb-8a07-0a2537c5b962.png)

2020-11-10 11:23 UTC, EvanceKao commented
哪尼QQ
驗過才推的，可能有不穩定的地方

2020-11-10 11:26 UTC, andrew0928 requested changes
測試失敗

2020-11-10 11:27 UTC, andrew0928 commented
平行處理... 時好時壞很正常 XDD

2020-11-10 11:29 UTC, andrew0928 commented
平行處理的副作用，看來多跑幾次答案都不同。

![image](https://user-images.githubusercontent.com/15281111/98668536-fb174f80-238a-11eb-9cc3-702fb5c634bd.png)
![image](https://user-images.githubusercontent.com/15281111/98668570-05d1e480-238b-11eb-8446-e4d07c7beef2.png)

2020-11-10 11:30 UTC, EvanceKao commented
我難過

2020-11-11 13:38 UTC, EvanceKao commented
> 平行處理的副作用，看來多跑幾次答案都不同。
> 
> ![image](https://user-images.githubusercontent.com/15281111/98668536-fb174f80-238a-11eb-9cc3-702fb5c634bd.png)
> ![image](https://user-images.githubusercontent.com/15281111/98668570-05d1e480-238b-11eb-8446-e4d07c7beef2.png)

嘗試修復非同步造成的錯誤

2020-11-12 08:55 UTC, merged